services:
  - type: web
    name: discord-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
